import Foundation

public struct SgcoopStore: Identifiable, Hashable {
    public var id: String { code }
    public let code: String
    public let shortName: String
    public let fullName: String

    public init(code: String, shortName: String, fullName: String) {
        self.code = code
        self.shortName = shortName
        self.fullName = fullName
    }
}

public enum SgcoopStores {
    public static let list: [SgcoopStore] = [
        SgcoopStore(code: "151", shortName: "CQUYNH", fullName: "Co.opmart Cống Quỳnh"),
        SgcoopStore(code: "161", shortName: "XLHN", fullName: "Co.opmart Xa Lộ Hà Nội"),
        SgcoopStore(code: "505", shortName: "LTK", fullName: "Co.opmart Lý Thường Kiệt"),
        SgcoopStore(code: "516", shortName: "BDUONG", fullName: "Co.opmart Bình Dương"),
        SgcoopStore(code: "130", shortName: "RMIEU", fullName: "Co.opmart Rạch Miễu"),
        SgcoopStore(code: "120", shortName: "VLONG", fullName: "Co.opmart Vĩnh Long"),
        SgcoopStore(code: "141", shortName: "NAT", fullName: "Co.opmart Nguyễn Ảnh Thủ"),
        SgcoopStore(code: "159", shortName: "HTP", fullName: "Co.opmart Huỳnh Tấn Phát"),
        SgcoopStore(code: "155", shortName: "NDC", fullName: "Co.opmart Nguyễn Đình Chiểu"),
        SgcoopStore(code: "112", shortName: "QNHON", fullName: "Co.opmart Quy Nhơn"),
        SgcoopStore(code: "123", shortName: "PKU", fullName: "Co.opmart Pleiku"),
        SgcoopStore(code: "187", shortName: "CTHO", fullName: "Co.opmart Cần Thơ"),
        SgcoopStore(code: "176", shortName: "TNINH", fullName: "Co.opmart Tây Ninh"),
        SgcoopStore(code: "122", shortName: "THOA", fullName: "Co.opmart Tuy Hòa"),
        SgcoopStore(code: "118", shortName: "PTHIET", fullName: "Co.opmart Phan Thiết"),
        SgcoopStore(code: "164", shortName: "HNOI", fullName: "Co.opmart Hà Nội"),
        SgcoopStore(code: "138", shortName: "BMT", fullName: "Co.opmart Buôn Ma Thuột"),
        SgcoopStore(code: "199", shortName: "BTRE", fullName: "Co.opmart Bến Tre"),
        SgcoopStore(code: "160", shortName: "NKIEM", fullName: "Co.opmart Ninh Kiều"),
        SgcoopStore(code: "514", shortName: "LAN", fullName: "Co.opmart Tân An (Long An)"),
        SgcoopStore(code: "522", shortName: "CMAU", fullName: "Co.opmart Cà Mau"),
        SgcoopStore(code: "127", shortName: "BPHUOC", fullName: "Co.opmart Đồng Xoài (Bình Phước)"),
        SgcoopStore(code: "124", shortName: "BHOA", fullName: "Co.opmart Biên Hòa"),
        SgcoopStore(code: "140", shortName: "NTRANG", fullName: "Co.opmart Nha Trang"),
        SgcoopStore(code: "128", shortName: "DNANG", fullName: "Co.opmart Đà Nẵng"),
        SgcoopStore(code: "158", shortName: "PVH", fullName: "Co.opmart Phan Văn Hớn"),
        SgcoopStore(code: "178", shortName: "HBINH", fullName: "Co.opmart Hòa Bình"),
        SgcoopStore(code: "512", shortName: "QBINH", fullName: "Co.opmart Quảng Bình"),
        SgcoopStore(code: "132", shortName: "TKY", fullName: "Co.opmart Tam Kỳ"),
        SgcoopStore(code: "131", shortName: "VTAU", fullName: "Co.opmart Vũng Tàu"),
        SgcoopStore(code: "147", shortName: "STRANG", fullName: "Co.opmart Sóc Trăng"),
        SgcoopStore(code: "175", shortName: "CCHI", fullName: "Co.opmart Củ Chi"),
        SgcoopStore(code: "145", shortName: "QNGAI", fullName: "Co.opmart Quảng Ngãi"),
        SgcoopStore(code: "197", shortName: "CLANH", fullName: "Co.opmart Cao Lãnh"),
        SgcoopStore(code: "148", shortName: "THA", fullName: "Co.opmart Thuận An"),
        SgcoopStore(code: "119", shortName: "LXUYEN", fullName: "Co.opmart Long Xuyên"),
        SgcoopStore(code: "157", shortName: "PLAM", fullName: "Co.opmart Phú Lâm"),
        SgcoopStore(code: "167", shortName: "QTRI", fullName: "Co.opmart Quảng Trị"),
        SgcoopStore(code: "189", shortName: "TBANG", fullName: "Co.opmart Trảng Bàng"),
        SgcoopStore(code: "570", shortName: "TLOI", fullName: "Co.opmart Thắng Lợi"),
        SgcoopStore(code: "136", shortName: "BTAN", fullName: "Co.opmart Bình Tân"),
        SgcoopStore(code: "137", shortName: "HUE", fullName: "Co.opmart Huế"),
        SgcoopStore(code: "142", shortName: "BLIEU2", fullName: "Co.opmart Bạc Liêu"),
        SgcoopStore(code: "134", shortName: "TLV", fullName: "Co.opmart Tháp Mười / Thanh Lương"),
        SgcoopStore(code: "162", shortName: "PVT", fullName: "Co.opmart Phan Văn Trị"),
        SgcoopStore(code: "530", shortName: "CVA", fullName: "Co.opmart Chu Văn An"),
        SgcoopStore(code: "173", shortName: "BLOC", fullName: "Co.opmart Bảo Lộc"),
        SgcoopStore(code: "153", shortName: "HGIANG", fullName: "Co.opmart Hậu Giang"),
        SgcoopStore(code: "154", shortName: "PTHO", fullName: "Co.opmart Phú Thọ"),
        SgcoopStore(code: "133", shortName: "NLOC", fullName: "Co.opmart Nhiêu Lộc"),
        SgcoopStore(code: "144", shortName: "KGIANG", fullName: "Co.opmart Kiên Giang"),
        SgcoopStore(code: "515", shortName: "BRIA", fullName: "Co.opmart Bà Rịa"),
        SgcoopStore(code: "196", shortName: "FCS", fullName: "Co.opmart Trung tâm phân phối FCS"),
        SgcoopStore(code: "503", shortName: "BDUONG2", fullName: "Co.opmart Bình Dương 2"),
        SgcoopStore(code: "506", shortName: "VATHANH", fullName: "Co.opmart Văn Thánh"),
        SgcoopStore(code: "185", shortName: "THHOA", fullName: "Co.opmart Thanh Hóa"),
        SgcoopStore(code: "114", shortName: "MTHO", fullName: "Co.opmart Mỹ Tho"),
        SgcoopStore(code: "150", shortName: "HTINH", fullName: "Co.opmart Hà Tĩnh"),
        SgcoopStore(code: "184", shortName: "RGIA", fullName: "Co.opmart Rạch Giá"),
        SgcoopStore(code: "517", shortName: "SDEC", fullName: "Co.opmart Sa Đéc"),
        SgcoopStore(code: "183", shortName: "HPHONG", fullName: "Co.opmart Hải Phòng"),
        SgcoopStore(code: "529", shortName: "TTHANH", fullName: "Co.opmart Tân Thành"),
        SgcoopStore(code: "513", shortName: "BLUC", fullName: "Co.opmart Bến Lức"),
        SgcoopStore(code: "541", shortName: "BTAN2", fullName: "Co.opmart Bình Tân 2"),
        SgcoopStore(code: "170", shortName: "TVINH", fullName: "Co.opmart Trà Vinh"),
        SgcoopStore(code: "528", shortName: "KTUM", fullName: "Co.opmart Kon Tum"),
        SgcoopStore(code: "532", shortName: "CLAY", fullName: "Co.opmart Cai Lậy"),
        SgcoopStore(code: "518", shortName: "GCONG", fullName: "Co.opmart Gò Công"),
        SgcoopStore(code: "507", shortName: "LGI", fullName: "Co.opmart La Gi"),
        SgcoopStore(code: "186", shortName: "BTRIEU", fullName: "Co.opmart Bình Triệu"),
        SgcoopStore(code: "511", shortName: "HTHANH", fullName: "Co.opmart Hòa Thành"),
        SgcoopStore(code: "174", shortName: "CRANH", fullName: "Co.opmart Cam Ranh"),
        SgcoopStore(code: "121", shortName: "VTHANH", fullName: "Co.opmart Vị Thanh"),
        SgcoopStore(code: "519", shortName: "TNOT", fullName: "Co.opmart Thốt Nốt"),
        SgcoopStore(code: "504", shortName: "DNONG", fullName: "Co.opmart Đắk Nông"),
        SgcoopStore(code: "152", shortName: "HMON", fullName: "Co.opmart Hóc Môn"),
        SgcoopStore(code: "171", shortName: "HGIANG2", fullName: "Co.opmart Hậu Giang 2"),
        SgcoopStore(code: "539", shortName: "PRI", fullName: "Co.opmart Phan Rí Cửa"),
        SgcoopStore(code: "135", shortName: "HVUONG", fullName: "Co.opmart Hùng Vương"),
        SgcoopStore(code: "179", shortName: "VPHUC", fullName: "Co.opmart Vĩnh Phúc"),
        SgcoopStore(code: "540", shortName: "CGIUOC", fullName: "Co.opmart Cần Giuộc"),
        SgcoopStore(code: "534", shortName: "GDAU", fullName: "Co.opmart Gò Dầu"),
        SgcoopStore(code: "542", shortName: "BTHUY", fullName: "Co.opmart Bình Thủy"),
        SgcoopStore(code: "524", shortName: "DVC", fullName: "Co.opmart Đỗ Văn Dậy"),
        SgcoopStore(code: "565", shortName: "TBINH", fullName: "Co.opmart Tam Bình"),
        SgcoopStore(code: "527", shortName: "CSE", fullName: "Co.opmart Chư Sê"),
        SgcoopStore(code: "523", shortName: "BHO", fullName: "Co.opmart Ba Hòn"),
        SgcoopStore(code: "526", shortName: "TCHAU", fullName: "Co.opmart Tân Châu"),
        SgcoopStore(code: "180", shortName: "CGIO", fullName: "Co.opmart Cần Giờ"),
        SgcoopStore(code: "520", shortName: "CDOC", fullName: "Co.opmart Châu Đốc"),
        SgcoopStore(code: "531", shortName: "HTIEN", fullName: "Co.opmart Hà Tiên"),
        SgcoopStore(code: "571", shortName: "ANHON", fullName: "Co.opmart An Nhơn"),
        SgcoopStore(code: "546", shortName: "DPHU", fullName: "Co.opmart Định Quán"),
        SgcoopStore(code: "567", shortName: "QMART", fullName: "Co.opmart Quang Trung"),
        SgcoopStore(code: "547", shortName: "STRA", fullName: "Co.opmart Sơn Trà"),
        SgcoopStore(code: "555", shortName: "SCA-LBien", fullName: "Co.opmart SCA Long Biên"),
        SgcoopStore(code: "508", shortName: "NBINH", fullName: "Co.opmart Ninh Bình"),
        SgcoopStore(code: "549", shortName: "SCA-HVT", fullName: "Co.opmart SCA Hoàng Văn Thụ"),
        SgcoopStore(code: "536", shortName: "DHAI", fullName: "Co.opmart Duyên Hải"),
        SgcoopStore(code: "502", shortName: "BGIANG", fullName: "Co.opmart Bắc Giang"),
        SgcoopStore(code: "569", shortName: "TMUOI", fullName: "Co.opmart Tháp Mười"),
        SgcoopStore(code: "535", shortName: "AGIANG", fullName: "Co.opmart An Giang"),
        SgcoopStore(code: "563", shortName: "TBIEN", fullName: "Co.opmart Tân Biên"),
        SgcoopStore(code: "533", shortName: "HNGU", fullName: "Co.opmart Hồng Ngự"),
        SgcoopStore(code: "561", shortName: "SCA-CTHANG", fullName: "Co.opmart SCA Cao Thắng"),
        SgcoopStore(code: "510", shortName: "DVD", fullName: "Co.opmart Đồng Văn Cống"),
        SgcoopStore(code: "557", shortName: "SCA-TNINH", fullName: "Co.opmart SCA Tây Ninh"),
        SgcoopStore(code: "572", shortName: "DPHO", fullName: "Co.opmart Đức Phổ"),
        SgcoopStore(code: "566", shortName: "CMGAR", fullName: "Co.opmart Cư M'gar"),
        SgcoopStore(code: "552", shortName: "SCA-Vic", fullName: "Co.opmart SCA Victoria"),
        SgcoopStore(code: "537", shortName: "VTRI", fullName: "Co.opmart Việt Trì"),
        SgcoopStore(code: "573", shortName: "CBE", fullName: "Co.opmart Cái Bè"),
        SgcoopStore(code: "554", shortName: "SCA-Goldensilk", fullName: "Co.opmart SCA Golden Silk"),
        SgcoopStore(code: "562", shortName: "TSON", fullName: "Co.opmart Từ Sơn"),
        SgcoopStore(code: "553", shortName: "SCA-Goldsilk", fullName: "Co.opmart SCA Goldsilk"),
        SgcoopStore(code: "509", shortName: "VLOCB", fullName: "Co.opmart Vĩnh Lộc B"),
        SgcoopStore(code: "538", shortName: "PDONG", fullName: "Co.opmart Phương Đông"),
        SgcoopStore(code: "545", shortName: "TCAN", fullName: "Co.opmart Tiểu Cần"),
        SgcoopStore(code: "574", shortName: "CMOI", fullName: "Co.opmart Chợ Mới"),
        SgcoopStore(code: "543", shortName: "CTHANH", fullName: "Co.opmart Châu Thành"),
        SgcoopStore(code: "556", shortName: "TOKY", fullName: "Co.opmart Tô Ký"),
        SgcoopStore(code: "564", shortName: "DMC", fullName: "Co.opmart Duyên Mộc"),
        SgcoopStore(code: "575", shortName: "PTH", fullName: "Co.opmart Phan Thiết 2")
    ]
}
